// GENERATED by scripts/derive-pynchon-line.mjs — do not hand-edit; re-run it instead.
//
// TWO DIFFERENT SETS, and they are not the same people (Sam, Aug 8): "all of the pynchon tree can get
// these titles but only rainbows in direct line to thomas."
//
//   GENERATION — every descendant of Hon. William Pynchon (Y00004), by depth below him. 0 is William
//     himself. Drives the TITLE, via generation.ts's own buildDescendantLabel, so the Pynchon line words
//     itself exactly as the Hooker line does (Son → Grandson → Great-Grandson → Fifth Generation …).
//   RAINBOW — only the direct line to Thomas Ruggles Pynchon Jr. (X03232) plus Jackson (HD6314), and
//     the mother at each step. Drives the BACKGROUND.
//
// Both are derived from the parent graph rather than listed, so neither can drift from the genealogy.
export const PYNCHON_LINE: ReadonlyArray<readonly [string, number | null, boolean]> = [
	['Y00004', 0, true], // Hon. William Pynchon
	['X03297', 1, true], // Major John Pynchon
	['X01014', 2, false], // Mary Smith Lord Hooker
	['X03298', 2, true], // Lt. Col. John C. Pynchon
	['X03300', 3, true], // Col. William Pynchon
	['X03220', 4, true], // Joseph Pynchon
	['X03221', 5, true], // Dr. Thomas Ruggles Pynchon
	['X03223', 6, true], // William Henry Ruggles Pynchon
	['X03225', 7, true], // William Lyon Pynchon
	['X03226', 7, false], // Rev. Thomas Ruggles Pynchon
	['X03228', 8, true], // William Harry Chichele Pynchon
	['X03230', 9, true], // Thomas Ruggles Pynchon Sr.
	['X03232', 10, true], // Thomas Ruggles Pynchon Jr.
	['HD6314', 11, true], // Jackson Pynchon
	['X01779', null, true], // Ann Andrew
	['X03219', null, true], // Sarah Ruggles Pynchon
	['X03222', null, true], // Rebecca Tomlinson Pynchon
	['X03224', null, true], // Mary Murdoch Pynchon
	['X03227', null, true], // Anna Payne Cogswell Pynchon
	['X03229', null, true], // Caroline Moyses Pynchon
	['X03231', null, true], // Catherine Frances Bennett Pynchon
	['X03299', null, true], // Margaret Hubbard Pynchon
	['X03301', null, true], // Katherine Brewer Pynchon
	['X03851', null, true], // Amy Wyllys Pynchon
];

const GEN = new Map<string, number | null>(PYNCHON_LINE.map(([id, g]) => [id, g]));
const RAINBOW = new Set<string>(PYNCHON_LINE.filter(([, , r]) => r).map(([id]) => id));

/** Does this person's card carry the line's spectrum? Direct line only. */
export function isPynchonKin(id: string | null | undefined): boolean {
	return !!id && RAINBOW.has(id);
}

/** Depth below the founder (0 = William), or null if they are not a descendant of his. */
export function pynchonGeneration(id: string | null | undefined): number | null {
	if (!id) return null;
	return GEN.get(id) ?? null;
}
